#get products
###
GET http://localhost:3001/api/products

#create a product
###
POST http://localhost:3001/api/products
Content-Type: application/json
 
 {
     "name": "Aromatherapy",
     "price": 32.00,
     "description": " stylish diffuser and oil set."
  }

#get one product
###
GET http://localhost:3001/api/products/68163b607861fefd6bb3cd07

#update a product
###
PUT http://localhost:3001/api/products/68163c177861fefd6bb3cd15
Content-Type: application/json

{
    "price": 33.99
}

#delete a product
###
DELETE http://localhost:3001/api/products/68164051e79131f457f1363b