
###
# @token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODE0ZmY2ZTEzYThmMWZhODRiNDY2NzQiLCJpYXQiOjE3NDYyMDczMjMsImV4cCI6MTc0NjIxMDkyM30.SS06rlL5sNUQxqJ0kiSrf74JzINHv-nGJqGC3mDEDCA

GET http://localhost:3001/api/books
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODE0ZmY2ZTEzYThmMWZhODRiNDY2NzQiLCJpYXQiOjE3NDYyMDczMjMsImV4cCI6MTc0NjIxMDkyM30.SS06rlL5sNUQxqJ0kiSrf74JzINHv-nGJqGC3mDEDCA

###
POST http://localhost:3001/api/books
Content-Type: application/json

{
    "title":"123",
    "author":"Charles ",
    "description":"wanted and asked for more"
}


###
GET http://localhost:3001/api/books/6814cfe544d8274ee762cc8b


###
PUT http://localhost:3001/api/books/6814f94aa433dc92fd27ec93
Content-Type: application/json

{
    "title":"The Book of Eli",
    "author":"Washington Denzel",
    "description":"The book of Eli, i think"
}


###
DELETE http://localhost:3001/api/books/6814d88b5132d50fc20a8430


# Register User
###
POST http://localhost:3001/api/register
Content-Type: application/json

{
    "username":"gwine",
    "password":"abc123"
}

# Register User
###
POST http://localhost:3001/api/register
Content-Type: application/json

{
    "username":"bola",
    "password":"abimbim"
}

#Login User
###
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username":"gwine",
    "password":"abc123"
}

#token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODE0ZmY2ZTEzYThmMWZhODRiNDY2NzQiLCJpYXQiOjE3NDYyMDczMjMsImV4cCI6MTc0NjIxMDkyM30.SS06rlL5sNUQxqJ0kiSrf74JzINHv-nGJqGC3mDEDCA