#upload a book
###
POST http://localhost:5001/upload-book
Content-Type: application/json

{
    "authorName": "Denise Hunter",
    "imageURL": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1726077541i/216052965.jpg",
    "category": "Christian Fiction",
    "bookDescription": "Maggie Reynolds is finally ready for love",
    "bookTitle": "The Summer of You and Me",
    "bookPdfUrl": "https://example.com/gatsby_pdf.pdf"
  }

#get all books
###
GET http://localhost:5001/all-books

# update a book
###
PATCH http://localhost:5001/book/681f43504ea24a42fa72ba0d
Content-Type: application/json

{
    "imageUrl":"https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1729890029i/220838350.jpg",
    "authorName":"Iliana Xander",
    "category":"Mystery, Crime, Fiction, Thriller, Suspense",
    "bookDescription":"Mackenzie Casper is a brilliant student.",
    "bookTitle":"Love, Mom",
    "bookPdfUrl":""
}

#delete a book
###
DELETE http://localhost:5001/book/681f42d14ea24a42fa72ba04


#get book using category
###
GET http://localhost:5001/all-book/?category=Horror

# get one book
###
GET http://localhost:5001/book/681f43504ea24a42fa72ba0d
