#upload a book
###
POST http://localhost:5001/upload-book
Content-Type: application/json

{
    "authorName": "F. Scott Fitzgerald",
    "imageURL": "https://example.com/gatsby_image.jpg",
    "category": "Classic",
    "bookDescription": "A tale of wealth, love, and the American Dream in the Jazz Age.",
    "bookTitle": "The Great Gatsby",
    "bookPdfUrl": "https://example.com/gatsby_pdf.pdf"
  }

#get all books
###
GET http://localhost:5001/all-books

# update a book
###
PATCH http://localhost:5001/book/681f42d14ea24a42fa72ba04
Content-Type: application/json

{
    "authorName":"Abimbola Jennifer",
    "bookTitle":"Working with young minds"
}